### ISSUE TITLE
Filtros

### ISSUE THREAD

**Issue by evicsouza** [ifpe-cti/AdoPet#12]
Filtrar os animais por sexo, idade e espécie.

**Comment by fabriciofx** [comment]
@evicsouza Note que o título da issue está muito genérico: filtrar o quê? Em qual contexto? Além disso: é você que vai cuidar disso?

**Comment by evicsouza** [comment]
@fabriciofx 
Está detalhado na descrição, acredito que ela sirva para isso (se não for o caso eu posso corrigir).
Estamos colocando nas issues tudo que tem pra fazer sem dividir quem faz qual coisa (a princípio), por isso não estamos colocando labels para não confundir com o que já foi dividido.
