### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/AdoPet#128]
1. Criar diagrama de classes (http://www.lucidchart.com)
2. Salvar o id do usuário após login (https://alligator.io/js/introduction-localstorage-sessionstorage/)
3. Trabalhar no perfil do usuário
4. Trabalhar na adoção

**Comment by EmelyMelo** [comment]
![adopet - diagrama de classe](https://user-images.githubusercontent.com/26662684/47109236-20751600-d224-11e8-8bd1-0d676d7f5b63.png)
