### ISSUE TITLE
Adicionar membros no console do Firebase

### ISSUE THREAD

**Issue by evicsouza** [ifpe-cti/AdoPet#18]
Como faz pra dar permissão a alguém no console do firebase? 
Emely criou o projeto e eu não consigo entrar pq diz que o projeto não existe ou eu não tenho permissão pra ver. Emely já colocou na parte de adicionar um membro, mas continuo com o mesmo problema.

**Comment by lsoaresesilva** [comment]
Você precisa adicionar a permissão de leitura para todos:

// Allow read/write access to all users under any conditions
// Warning: **NEVER** use this rule set in production; it allows
// anyone to overwrite your entire database.
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
OBS: depois mudamos isto para restringir apenas ao próprio app, por enquanto usa isto.

Isto deve ser feito na Aba de regras, dentro do Firestore console.

**Comment by evicsouza** [comment]
Obrigada

**Comment by fabriciofx** [comment]
@lsoaresesilva Se você utilizar colocar o código entre ``` ele mantém a formatação #ficaadica.

**Comment by lsoaresesilva** [comment]
@fabriciofx feito: https://github.com/ifpe-cti/modelo-projeto-ppo/commit/a8f1374347d797f50008a16cc8edb839c662cffe
