### ISSUE TITLE
Adicionar as estórias do usuário como issues

### ISSUE THREAD

**Issue by lsoaresesilva** [ifpe-cti/AdoPet#19]
Para cada estória, adicionar como uma issue. Na descrição, descrever brevemente a estória, colocar também os testes de aceitação e a prioridade da mesma.

**Comment by fabriciofx** [comment]
@lsoaresesilva Te convido a submeter um documento no formato markdown para o [modelo-projeto-ppo](https://github.com/ifpe-cti/modelo-projeto-ppo) contento um guia de como escrever as User Stories para o projeto.
